#! /bin/bash
flt=''
for run in $*; do
  if [ $run = "-f" ]; then
    flt=F
  else
    echo $run
    [ -d $run$flt ] || mkdir $run$flt
    scp htwgse:/home/HTW/anal/$run/*.mat $run$flt
    [ -n "$flt" ] && scp htwgse:/home/HTW/raw/flight/$run/HTW.log $run$flt/HTW.log
  fi
done
