function phtwtst(varargin);
% phtwtst( [...] );
% Temp Sensors Temp
h = timeplot({'TS1_T','TS2_T','TS3_T'}, ...
      'Temp Sensors Temp', ...
      'Temp', ...
      {'TS1\_T','TS2\_T','TS3\_T'}, ...
      varargin{:} );
