function phtwme_statusps(varargin);
% phtwme_statusps( [...] );
% ME Status Plate Status
h = timeplot({'Plate_DevStatus'}, ...
      'ME Status Plate Status', ...
      'Plate Status', ...
      {'Plate\_DevStatus'}, ...
      varargin{:} );
