function phtwme_statuscell_status(varargin);
% phtwme_statuscell_status( [...] );
% ME Status Cell Status
h = timeplot({'Cell_DevStatus'}, ...
      'ME Status Cell Status', ...
      'Cell Status', ...
      {'Cell\_DevStatus'}, ...
      varargin{:} );
