function phtwmecell_temp(varargin);
% phtwmecell_temp( [...] );
% ME Cell Temp
h = timeplot({'Cell_T','Cell_Set_T','Cell_Sink_T'}, ...
      'ME Cell Temp', ...
      'Cell Temp', ...
      {'Cell\_T','Cell\_Set\_T','Cell\_Sink\_T'}, ...
      varargin{:} );
