function phtwcommandsi(varargin);
% phtwcommandsi( [...] );
% Commands I
h = timeplot({'Cmd0_I','Cmd1_I','Cmd2_I','Cmd7_I','Cmd8_I','Cmd9_I','Cmd11_I','Cmd12_I','Cmd13_I'}, ...
      'Commands I', ...
      'I', ...
      {'0','1','2','7','8','9','11','12','13'}, ...
      varargin{:} );
