function phtwmeerstettert(varargin);
% phtwmeerstettert( [...] );
% Meerstetter Temp
h = timeplot({'LTE_T','LTE_Sink_T','LTE_Set_T'}, ...
      'Meerstetter Temp', ...
      'Temp', ...
      {'LTE\_T','LTE\_Sink\_T','LTE\_Set\_T'}, ...
      varargin{:} );
