function phtwiwgat(varargin);
% phtwiwgat( [...] );
% Attitude Track
h = timeplot({'Track','True_Hdg'}, ...
      'Attitude Track', ...
      'Track', ...
      {'Track','True\_Hdg'}, ...
      varargin{:} );
