function phtwtsc(varargin);
% phtwtsc( [...] );
% Temp Sensors Count
h = timeplot({'TS1_cnt','TS2_cnt','TS3_cnt'}, ...
      'Temp Sensors Count', ...
      'Count', ...
      {'TS1\_cnt','TS2\_cnt','TS3\_cnt'}, ...
      varargin{:} );
