function phtwme_statuslpvs(varargin);
% phtwme_statuslpvs( [...] );
% ME Status LPV Status
h = timeplot({'LPV_DevStatus'}, ...
      'ME Status LPV Status', ...
      'LPV Status', ...
      {'LPV\_DevStatus'}, ...
      varargin{:} );
