function phtwter(varargin);
% phtwter( [...] );
% TE Rovers
h = timeplot({'Rov1T','Rov2T','Rov3T','Rov4T','Rov5T'}, ...
      'TE Rovers', ...
      'Rovers', ...
      {'1','2','3','4','5'}, ...
      varargin{:} );
