function phtwmemescell_stale(varargin);
% phtwmemescell_stale( [...] );
% ME Stale Cell Stale
h = timeplot({'Cell_Stale'}, ...
      'ME Stale Cell Stale', ...
      'Cell Stale', ...
      {'Cell\_Stale'}, ...
      varargin{:} );
