function phtwfmksaff(varargin);
% phtwfmksaff( [...] );
% MKS Air F Flow
h = timeplot({'AirF_Set','AirF_Flow'}, ...
      'MKS Air F Flow', ...
      'Air F Flow', ...
      {'AirF\_Set','AirF\_Flow'}, ...
      varargin{:} );
