function phtwmemedpvc(varargin);
% phtwmemedpvc( [...] );
% ME DPV Current
h = timeplot({'DPV_OutputCurrent'}, ...
      'ME DPV Current', ...
      'Current', ...
      {'DPV\_OutputCurrent'}, ...
      varargin{:} );
