function phtwhk_qcli_statrw(varargin);
% phtwhk_qcli_statrw( [...] );
% QCLI stat rw
h = timeplot({'QCLI_rw'}, ...
      'QCLI stat rw', ...
      'rw', ...
      {'QCLI\_rw'}, ...
      varargin{:} );
