function phtwdfixflt(varargin);
% phtwdfixflt( [...] );
% icosfitd fixflt
h = timeplot({'icosd_fixflt'}, ...
      'icosfitd fixflt', ...
      'fixflt', ...
      {'icosd\_fixflt'}, ...
      varargin{:} );
