function phtwqclistatus(varargin);
% phtwqclistatus( [...] );
% QCLI Status
h = ne_dstat({
  'QCLI_loc', 'QCLI_s', 3; ...
	'QCLI_lot', 'QCLI_s', 4; ...
	'QCLI_dot', 'QCLI_s', 5; ...
	'QCLI_waveerr', 'QCLI_s', 8; ...
	'QCLI_ready', 'QCLI_s', 9; ...
	'QCLI_cordte', 'QCLI_s', 11; ...
	'QCLI_laser', 'QCLI_s', 12; ...
	'QCLI_cmderr', 'QCLI_s', 13; ...
	'QCLI_cksum', 'QCLI_s', 14; ...
	'QCLI_busy', 'QCLI_s', 15; ...
	'QCLI_Reset_DS', 'DS84A', 2 }, 'Status', varargin{:} );
