function phtwmkshkstale(varargin);
% phtwmkshkstale( [...] );
% MKS HK Stale
h = timeplot({'AirF_Stale','BubF_Stale','MKS_Stale'}, ...
      'MKS HK Stale', ...
      'Stale', ...
      {'AirF\_Stale','BubF\_Stale','MKS\_Stale'}, ...
      varargin{:} );
