function phtwiwg1_iwg1_stattd(varargin);
% phtwiwg1_iwg1_stattd( [...] );
% IWG1 Stat T Drift
h = timeplot({'TDDrift','TDrift'}, ...
      'IWG1 Stat T Drift', ...
      'T Drift', ...
      {'TDDrift','TDrift'}, ...
      varargin{:} );
