function phtwpdacsais(varargin);
% phtwpdacsais( [...] );
% PDACS AI Stat
h = ne_dstat({
  '0', 'AIStat', 0; ...
	'1', 'AIStat', 1; ...
	'2', 'AIStat', 2; ...
	'3', 'AIStat', 3; ...
	'4', 'AIStat', 4; ...
	'5', 'AIStat', 5; ...
	'6', 'AIStat', 6; ...
	'7', 'AIStat', 7; ...
	'8', 'AIStat', 8; ...
	'9', 'AIStat', 9; ...
	'10', 'AIStat', 10; ...
	'11', 'AIStat', 11 }, 'AI Stat', varargin{:} );
