function phtwmainssv(varargin);
% phtwmainssv( [...] );
% Mains Status V
h = timeplot({'Mains_I2C_Status','Mains_ADC_Status'}, ...
      'Mains Status V', ...
      'Status V', ...
      {'Mains\_I2C\_Status','Mains\_ADC\_Status'}, ...
      varargin{:} );
