function phtwmemecs(varargin);
% phtwmemecs( [...] );
% ME Cover Status
h = timeplot({'Cover_DevStatus'}, ...
      'ME Cover Status', ...
      'Status', ...
      {'Cover\_DevStatus'}, ...
      varargin{:} );
