function phtwme_statusbcs(varargin);
% phtwme_statusbcs( [...] );
% ME Status Bub C Status
h = timeplot({'BubC_DevStatus'}, ...
      'ME Status Bub C Status', ...
      'Bub C Status', ...
      {'BubC\_DevStatus'}, ...
      varargin{:} );
