function phtwmemescs(varargin);
% phtwmemescs( [...] );
% ME Stale Cover Stale
h = timeplot({'Cover_Stale'}, ...
      'ME Stale Cover Stale', ...
      'Cover Stale', ...
      {'Cover\_Stale'}, ...
      varargin{:} );
