function phtwmeltet(varargin);
% phtwmeltet( [...] );
% ME LTE Temp
h = timeplot({'LTE_T','LTE_Set_T','LTE_Sink_T'}, ...
      'ME LTE Temp', ...
      'Temp', ...
      {'LTE\_T','LTE\_Set\_T','LTE\_Sink\_T'}, ...
      varargin{:} );
