function phtwfixflt(varargin);
% phtwfixflt( [...] );
% icosfitd fixflt
h = timeplot({'icosd_fixflt'}, ...
      'icosfitd fixflt', ...
      'fixflt', ...
      {'icosd\_fixflt'}, ...
      varargin{:} );
