function phtwwvs(varargin);
% phtwwvs( [...] );
% Wind Vert Speed
h = timeplot({'Vert_Wind_Spd'}, ...
      'Wind Vert Speed', ...
      'Vert Speed', ...
      {'Vert\_Wind\_Spd'}, ...
      varargin{:} );
