function phtwqcli_statmode(varargin);
% phtwqcli_statmode( [...] );
% QCLI stat mode
h = timeplot({'QCLI_mode'}, ...
      'QCLI stat mode', ...
      'mode', ...
      {'QCLI\_mode'}, ...
      varargin{:} );
