function phtwmemeslpvs(varargin);
% phtwmemeslpvs( [...] );
% ME Stale LPV Stale
h = timeplot({'LPV_Stale'}, ...
      'ME Stale LPV Stale', ...
      'LPV Stale', ...
      {'LPV\_Stale'}, ...
      varargin{:} );
