function phtwmelpvt(varargin);
% phtwmelpvt( [...] );
% ME LPV Temp
h = timeplot({'LPV_T','LPV_Set_T','LPV_Sink_T'}, ...
      'ME LPV Temp', ...
      'Temp', ...
      {'LPV\_T','LPV\_Set\_T','LPV\_Sink\_T'}, ...
      varargin{:} );
