function phtwmebcv(varargin);
% phtwmebcv( [...] );
% ME Bub C Voltage
h = timeplot({'BubC_OutputVoltage'}, ...
      'ME Bub C Voltage', ...
      'Voltage', ...
      {'BubC\_OutputVoltage'}, ...
      varargin{:} );
