function phtwme_statusltes(varargin);
% phtwme_statusltes( [...] );
% ME Status LTE Status
h = timeplot({'LTE_DevStatus'}, ...
      'ME Status LTE Status', ...
      'LTE Status', ...
      {'LTE\_DevStatus'}, ...
      varargin{:} );
