function phtwfmkshkack2(varargin);
% phtwfmkshkack2( [...] );
% MKS HK ACK2
h = timeplot({'AirF_ACK2','BubF_ACK2'}, ...
      'MKS HK ACK2', ...
      'ACK2', ...
      {'AirF\_ACK2','BubF\_ACK2'}, ...
      varargin{:} );
