function phtwmecs(varargin);
% phtwmecs( [...] );
% ME Cell Status
h = timeplot({'Cell_DevStatus'}, ...
      'ME Cell Status', ...
      'Cell Status', ...
      {'Cell\_DevStatus'}, ...
      varargin{:} );
