function phtwsspnsr(varargin);
% phtwsspnsr( [...] );
% SSP NSR
h = timeplot({'SSP_noise_pct0','SSP_noise_pct1'}, ...
      'SSP NSR', ...
      'NSR', ...
      {'SSP\_noise\_pct0','SSP\_noise\_pct1'}, ...
      varargin{:} );
