function phtwct(varargin);
% phtwct( [...] );
% Cell T
h = timeplot({'Cel1T','Cel2T','SGs1T','SGs2T','TS1_T','TS2_T'}, ...
      'Cell T', ...
      'T', ...
      {'Cel1T','Cel2T','SGs1T','SGs2T','TS1\_T','TS2\_T'}, ...
      varargin{:} );
