function phtwhk_qcli_staterr(varargin);
% phtwhk_qcli_staterr( [...] );
% QCLI stat err
h = timeplot({'QCLI_err'}, ...
      'QCLI stat err', ...
      'err', ...
      {'QCLI\_err'}, ...
      varargin{:} );
