function phtwmeebce(varargin);
% phtwmeebce( [...] );
% ME Errors Bub C Errors
h = timeplot({'BubC_ErrorNumber','BubC_ErrorInstance','BubC_ErrorParameter'}, ...
      'ME Errors Bub C Errors', ...
      'Bub C Errors', ...
      {'BubC\_ErrorNumber','BubC\_ErrorInstance','BubC\_ErrorParameter'}, ...
      varargin{:} );
