function phtwqcli_statfifodep(varargin);
% phtwqcli_statfifodep( [...] );
% QCLI stat fifodep
h = timeplot({'QCLI_fifodep'}, ...
      'QCLI stat fifodep', ...
      'fifodep', ...
      {'QCLI\_fifodep'}, ...
      varargin{:} );
