function phtwgdc(varargin);
% phtwgdc( [...] );
% Gas Deck Commands
h = ne_dstat({
  'Edw_Vlv_DS', 'DS822', 12; ...
	'Edw_Vlv_S', 'DS844', 12; ...
	'Gas_Flw_Open_DS', 'DS834', 0; ...
	'Gas_Flw_Closed_DS', 'DS834', 1; ...
	'Bub_Gas_Flw_Open_DS', 'DS834', 2; ...
	'Bub_Gas_Flw_Closed_DS', 'DS834', 3; ...
	'Gas_Vlv_D_DS', 'DS84A', 3; ...
	'Bub_Gas_Vlv_D_DS', 'DS84A', 4; ...
	'Bub_Vlv_Flw_D_DS', 'DS84A', 5 }, 'Commands', varargin{:} );
