function phtwhk_qcli_statsn(varargin);
% phtwhk_qcli_statsn( [...] );
% QCLI stat SN
h = timeplot({'SSP_SN'}, ...
      'QCLI stat SN', ...
      'SN', ...
      {'SSP\_SN'}, ...
      varargin{:} );
