function phtwme_cellt(varargin);
% phtwme_cellt( [...] );
% ME Cell Temp
h = timeplot({'Cell_T','Cell_Set_T','Cell_Sink_T'}, ...
      'ME Cell Temp', ...
      'Temp', ...
      {'Cell\_T','Cell\_Set\_T','Cell\_Sink\_T'}, ...
      varargin{:} );
