function phtwmainst(varargin);
% phtwmainst( [...] );
% Mains Temps
h = timeplot({'Mains_Ch0T','Mains_Ch1T','Mains_Ch2T','Mains_Ch3T','Mains_PMotT','Mains_PumpT'}, ...
      'Mains Temps', ...
      'Temps', ...
      {'Mains\_Ch0T','Mains\_Ch1T','Mains\_Ch2T','Mains\_Ch3T','Mains\_PMotT','Mains\_PumpT'}, ...
      varargin{:} );
