function phtwhktts(varargin);
% phtwhktts( [...] );
% Temps Temp Sensors
h = timeplot({'TS3_T'}, ...
      'Temps Temp Sensors', ...
      'Temp Sensors', ...
      {'TS3\_T'}, ...
      varargin{:} );
