function phtwmebct(varargin);
% phtwmebct( [...] );
% ME Bub C Temp
h = timeplot({'BubC_T','BubC_Set_T','BubC_Sink_T'}, ...
      'ME Bub C Temp', ...
      'Bub C Temp', ...
      {'BubC\_T','BubC\_Set\_T','BubC\_Sink\_T'}, ...
      varargin{:} );
