function phtwme_staleps(varargin);
% phtwme_staleps( [...] );
% ME Stale Plate Stale
h = timeplot({'Plate_Stale'}, ...
      'ME Stale Plate Stale', ...
      'Plate Stale', ...
      {'Plate\_Stale'}, ...
      varargin{:} );
