function phtwmsspt(varargin);
% phtwmsspt( [...] );
% Misc SSP T
h = timeplot({'SSP_T_FPGA','SSP_T_HtSink','SSP_T','VtoIT','QCLIT'}, ...
      'Misc SSP T', ...
      'SSP T', ...
      {'SSP\_T\_FPGA','SSP\_T\_HtSink','SSP\_T','VtoIT','QCLIT'}, ...
      varargin{:} );
