function phtwhkts(varargin);
% phtwhkts( [...] );
% Temps Skin
h = timeplot({'Skn1T','Skn2T','Skn3T','Skn4T','Skn5T'}, ...
      'Temps Skin', ...
      'Skin', ...
      {'1','2','3','4','5'}, ...
      varargin{:} );
