function phtwct(varargin);
% phtwct( [...] );
% Cell T
h = timeplot({'Cel1T','Cel2T','SGs1T','SGs2T'}, ...
      'Cell T', ...
      'T', ...
      {'Cel1T','Cel2T','SGs1T','SGs2T'}, ...
      varargin{:} );
