function phtwmemeecell_errors(varargin);
% phtwmemeecell_errors( [...] );
% ME Errors Cell Errors
h = timeplot({'Cell_ErrorNumber','Cell_ErrorInstance','Cell_ErrorParameter'}, ...
      'ME Errors Cell Errors', ...
      'Cell Errors', ...
      {'Cell\_ErrorNumber','Cell\_ErrorInstance','Cell\_ErrorParameter'}, ...
      varargin{:} );
