function phtwpdacst(varargin);
% phtwpdacst( [...] );
% PDACS T
h = timeplot({'PC__T','PS__T','SSP_T'}, ...
      'PDACS T', ...
      'T', ...
      {'PC\_\_T','PS\_\_T','SSP\_T'}, ...
      varargin{:} );
