function phtwlpvptrhs(varargin);
% phtwlpvptrhs( [...] );
% LPV PTRH Status
h = ne_dstat({
  '0', 'LPV_PTRHS', 0; ...
	'1', 'LPV_PTRHS', 1; ...
	'2', 'LPV_PTRHS', 2; ...
	'3', 'LPV_PTRHS', 3; ...
	'4', 'LPV_PTRHS', 4; ...
	'5', 'LPV_PTRHS', 5; ...
	'6', 'LPV_PTRHS', 6; ...
	'7', 'LPV_PTRHS', 7; ...
	'8', 'LPV_PTRHS', 8; ...
	'9', 'LPV_PTRHS', 9; ...
	'10', 'LPV_PTRHS', 10; ...
	'11', 'LPV_PTRHS', 11 }, 'Status', varargin{:} );
