function phtwmemebcs(varargin);
% phtwmemebcs( [...] );
% ME Bub C Status
h = timeplot({'BubC_DevStatus'}, ...
      'ME Bub C Status', ...
      'Status', ...
      {'BubC\_DevStatus'}, ...
      varargin{:} );
