function phtwmeerstetterstale(varargin);
% phtwmeerstetterstale( [...] );
% Meerstetter Stale
h = timeplot({'LTE_Stale'}, ...
      'Meerstetter Stale', ...
      'Stale', ...
      {'LTE\_Stale'}, ...
      varargin{:} );
