function phtwmecc(varargin);
% phtwmecc( [...] );
% ME Cover Current
h = timeplot({'Cover_OutputCurrent'}, ...
      'ME Cover Current', ...
      'Current', ...
      {'Cover\_OutputCurrent'}, ...
      varargin{:} );
