function phtwfgdt(varargin);
% phtwfgdt( [...] );
% Gas Deck T
h = timeplot({'GD_1T','GD_2T','GD_3T'}, ...
      'Gas Deck T', ...
      'T', ...
      {'GD\_1T','GD\_2T','GD\_3T'}, ...
      varargin{:} );
