function phtwqcli_statskip(varargin);
% phtwqcli_statskip( [...] );
% QCLI stat Skip
h = timeplot({'SSP_TS'}, ...
      'QCLI stat Skip', ...
      'Skip', ...
      {'SSP\_TS'}, ...
      varargin{:} );
