function phtwqcliw(varargin);
% phtwqcliw( [...] );
% QCLI Wave
h = timeplot({'QCLI_Wave','QCLI_Wave'}, ...
      'QCLI Wave', ...
      'Wave', ...
      {'QCLI\_Wave','QCLI\_Wave'}, ...
      varargin{:} );
