function phtwmedpvc(varargin);
% phtwmedpvc( [...] );
% ME DPV Current
h = timeplot({'DPV_OutputCurrent'}, ...
      'ME DPV Current', ...
      'Current', ...
      {'DPV\_OutputCurrent'}, ...
      varargin{:} );
