function phtwwvv(varargin);
% phtwwvv( [...] );
% Wind Vert Vel
h = timeplot({'Vert_Velocity'}, ...
      'Wind Vert Vel', ...
      'Vert Vel', ...
      {'Vert\_Velocity'}, ...
      varargin{:} );
