function phtwhk_mainss(varargin);
% phtwhk_mainss( [...] );
% Mains Status
h = ne_dstat({
  'PumpEn', 'Mains_Cmd_Status', 0; ...
	'PumpSA', 'Mains_Cmd_Status', 1; ...
	'PumpSB', 'Mains_Cmd_Status', 2; ...
	'MainsLED1', 'Mains_Cmd_Status', 3; ...
	'MainsLED2', 'Mains_Cmd_Status', 4; ...
	'MainsLED3', 'Mains_Cmd_Status', 5 }, 'Status', varargin{:} );
