function phtwmemebcc(varargin);
% phtwmemebcc( [...] );
% ME Bub C Current
h = timeplot({'BubC_OutputCurrent'}, ...
      'ME Bub C Current', ...
      'Current', ...
      {'BubC\_OutputCurrent'}, ...
      varargin{:} );
