function phtwme_statusdpvs(varargin);
% phtwme_statusdpvs( [...] );
% ME Status DPV Status
h = timeplot({'DPV_DevStatus'}, ...
      'ME Status DPV Status', ...
      'DPV Status', ...
      {'DPV\_DevStatus'}, ...
      varargin{:} );
