function phtwsspt(varargin);
% phtwsspt( [...] );
% SSP T
h = timeplot({'SSP_T_FPGA','SSP_T_HtSink','SSP_T','VtoIT','QCLIT'}, ...
      'SSP T', ...
      'T', ...
      {'SSP\_T\_FPGA','SSP\_T\_HtSink','SSP\_T','VtoIT','QCLIT'}, ...
      varargin{:} );
