function phtwmes(varargin);
% phtwmes( [...] );
% ME Stale
h = timeplot({'ME_Stale','LTE_Stale','LPV_Stale','Plate_Stale','Cover_Stale','Cell_Stale','DPV_Stale','BubC_Stale','ME_Stale'}, ...
      'ME Stale', ...
      'Stale', ...
      {'ME\_Stale','LTE\_Stale','LPV\_Stale','Plate\_Stale','Cover\_Stale','Cell\_Stale','DPV\_Stale','BubC\_Stale','ME\_Stale'}, ...
      varargin{:} );
