function phtwmes(varargin);
% phtwmes( [...] );
% ME Stale
h = timeplot({'ME_Stale','LTE_Stale','Cell_Stale','ME_Stale'}, ...
      'ME Stale', ...
      'Stale', ...
      {'ME\_Stale','LTE\_Stale','Cell\_Stale','ME\_Stale'}, ...
      varargin{:} );
