function phtwmesltes(varargin);
% phtwmesltes( [...] );
% ME Stale LTE Stale
h = timeplot({'LTE_Stale'}, ...
      'ME Stale LTE Stale', ...
      'LTE Stale', ...
      {'LTE\_Stale'}, ...
      varargin{:} );
