function phtwmemelpvc(varargin);
% phtwmemelpvc( [...] );
% ME LPV Current
h = timeplot({'LPV_OutputCurrent'}, ...
      'ME LPV Current', ...
      'Current', ...
      {'LPV\_OutputCurrent'}, ...
      varargin{:} );
