function phtwme_cellc(varargin);
% phtwme_cellc( [...] );
% ME Cell Current
h = timeplot({'Cell_OutputCurrent'}, ...
      'ME Cell Current', ...
      'Current', ...
      {'Cell\_OutputCurrent'}, ...
      varargin{:} );
