function phtwhktr(varargin);
% phtwhktr( [...] );
% Temps Rovers
h = timeplot({'Rov1T','Rov2T','Rov3T','Rov4T','Rov5T','Rov6T','Rov7T','Rov8T','Rov9T'}, ...
      'Temps Rovers', ...
      'Rovers', ...
      {'1','2','3','4','5','6','7','8','9'}, ...
      varargin{:} );
