function phtwqcli_staterr(varargin);
% phtwqcli_staterr( [...] );
% QCLI stat err
h = timeplot({'QCLI_err'}, ...
      'QCLI stat err', ...
      'err', ...
      {'QCLI\_err'}, ...
      varargin{:} );
