function phtwmebcs(varargin);
% phtwmebcs( [...] );
% ME Bub C Status
h = timeplot({'BubC_DevStatus'}, ...
      'ME Bub C Status', ...
      'Bub C Status', ...
      {'BubC\_DevStatus'}, ...
      varargin{:} );
