function phtwtssp(varargin);
% phtwtssp( [...] );
% Temps SSP
h = timeplot({'SSP_T_FPGA','SSP_T_HtSink'}, ...
      'Temps SSP', ...
      'SSP', ...
      {'SSP\_T\_FPGA','SSP\_T\_HtSink'}, ...
      varargin{:} );
