function phtwmect(varargin);
% phtwmect( [...] );
% ME Cover Temp
h = timeplot({'Cover_T','Cover_Set_T','Cover_Sink_T'}, ...
      'ME Cover Temp', ...
      'Temp', ...
      {'Cover\_T','Cover\_Set\_T','Cover\_Sink\_T'}, ...
      varargin{:} );
