function phtwhk_qcli_statskip(varargin);
% phtwhk_qcli_statskip( [...] );
% QCLI stat Skip
h = timeplot({'SSP_TS'}, ...
      'QCLI stat Skip', ...
      'Skip', ...
      {'SSP\_TS'}, ...
      varargin{:} );
