function phtwqcli_stats(varargin);
% phtwqcli_stats( [...] );
% QCLI stat Stale
h = timeplot({'QCLI_Stale','SSP_Stale'}, ...
      'QCLI stat Stale', ...
      'Stale', ...
      {'QCLI\_Stale','SSP\_Stale'}, ...
      varargin{:} );
