function phtwmemeltes(varargin);
% phtwmemeltes( [...] );
% ME LTE Status
h = timeplot({'LTE_DevStatus'}, ...
      'ME LTE Status', ...
      'Status', ...
      {'LTE\_DevStatus'}, ...
      varargin{:} );
