function phtwgdc(varargin);
% phtwgdc( [...] );
% Gas Deck Commands
h = ne_dstat({
  'Exh_Vlv_DS', 'DS08', 4; ...
	'Exh_Vlv_S', 'DS16', 4; ...
	'Gas_Vlv_D_DS', 'DS08', 0; ...
	'Gas_Vlv_D_S', 'DS16', 0; ...
	'Bub_In_Vlv_DS', 'DS14', 4; ...
	'Bub_Out_Vlv_DS', 'DS14', 5; ...
	'Det_TEC_DS', 'DS09', 0; ...
	'Det_TEC_S', 'DS17', 0; ...
	'Fwd_Exh_DS', 'DS09', 4; ...
	'Fwd_Exh_S', 'DS17', 4; ...
	'Aft_Exh_DS', 'DS09', 6; ...
	'Aft_Exh_S', 'DS17', 6 }, 'Commands', varargin{:} );
