function phtwhk_qcli_stats(varargin);
% phtwhk_qcli_stats( [...] );
% QCLI stat Stale
h = timeplot({'QCLI_Stale','SSP_Stale'}, ...
      'QCLI stat Stale', ...
      'Stale', ...
      {'QCLI\_Stale','SSP\_Stale'}, ...
      varargin{:} );
