function phtwmeltec(varargin);
% phtwmeltec( [...] );
% ME LTE Current
h = timeplot({'LTE_OutputCurrent'}, ...
      'ME LTE Current', ...
      'Current', ...
      {'LTE\_OutputCurrent'}, ...
      varargin{:} );
