function phtwhkpdacsptrh(varargin);
% phtwhkpdacsptrh( [...] );
% PDACS PTRH
h = ne_dstat({
  '0', 'DACS_PTRHS', 0; ...
	'1', 'DACS_PTRHS', 1; ...
	'2', 'DACS_PTRHS', 2; ...
	'3', 'DACS_PTRHS', 3; ...
	'4', 'DACS_PTRHS', 4; ...
	'5', 'DACS_PTRHS', 5; ...
	'6', 'DACS_PTRHS', 6; ...
	'7', 'DACS_PTRHS', 7; ...
	'8', 'DACS_PTRHS', 8; ...
	'9', 'DACS_PTRHS', 9; ...
	'10', 'DACS_PTRHS', 10; ...
	'11', 'DACS_PTRHS', 11 }, 'PTRH', varargin{:} );
