function phtwme_cellv(varargin);
% phtwme_cellv( [...] );
% ME Cell Voltage
h = timeplot({'Cell_OutputVoltage'}, ...
      'ME Cell Voltage', ...
      'Voltage', ...
      {'Cell\_OutputVoltage'}, ...
      varargin{:} );
