function phtwmepc(varargin);
% phtwmepc( [...] );
% ME Plate Current
h = timeplot({'Plate_OutputCurrent'}, ...
      'ME Plate Current', ...
      'Current', ...
      {'Plate\_OutputCurrent'}, ...
      varargin{:} );
