function phtwmesbcs(varargin);
% phtwmesbcs( [...] );
% ME Stale Bub C Stale
h = timeplot({'BubC_Stale'}, ...
      'ME Stale Bub C Stale', ...
      'Bub C Stale', ...
      {'BubC\_Stale'}, ...
      varargin{:} );
