function phtwhkpdacst(varargin);
% phtwhkpdacst( [...] );
% PDACS T
h = timeplot({'PC__T','PS__T','SSP_T','DACS_T1C','DACS_T2C'}, ...
      'PDACS T', ...
      'T', ...
      {'PC\_\_T','PS\_\_T','SSP\_T','DACS1','DACS2'}, ...
      varargin{:} );
