function phtwftvb(varargin);
% phtwftvb( [...] );
% TV Bits
h = ne_dstat({
  'C', 'TVStat', 7; ...
	'Z', 'TVStat', 6; ...
	'B', 'TVStat', 5; ...
	'A', 'TVStat', 4; ...
	'R', 'TVStat', 3; ...
	'D', 'TVStat', 2; ...
	'O', 'TVStat', 1; ...
	'I', 'TVStat', 0; ...
	'TVScan', 'IXStt', 1 }, 'Bits', varargin{:} );
