function phtwqclis(varargin);
% phtwqclis( [...] );
% QCLI Stale
h = timeplot({'QCLI_Stale','SSP_Stale'}, ...
      'QCLI Stale', ...
      'Stale', ...
      {'QCLI\_Stale','SSP\_Stale'}, ...
      varargin{:} );
