function phtwmes(varargin);
% phtwmes( [...] );
% ME Stale
h = timeplot({'ME_Stale','ME_Stale'}, ...
      'ME Stale', ...
      'Stale', ...
      {'ME\_Stale','ME\_Stale'}, ...
      varargin{:} );
