function phtwhkmtsc(varargin);
% phtwhkmtsc( [...] );
% Misc TS Counts
h = timeplot({'TS1_cnt','TS2_cnt','TS3_cnt'}, ...
      'Misc TS Counts', ...
      'TS Counts', ...
      {'TS1\_cnt','TS2\_cnt','TS3\_cnt'}, ...
      varargin{:} );
