function phtwdpvptrhs(varargin);
% phtwdpvptrhs( [...] );
% DPV PTRH Status
h = ne_dstat({
  '0', 'DPV_PTRHS', 0; ...
	'1', 'DPV_PTRHS', 1; ...
	'2', 'DPV_PTRHS', 2; ...
	'3', 'DPV_PTRHS', 3; ...
	'4', 'DPV_PTRHS', 4; ...
	'5', 'DPV_PTRHS', 5; ...
	'6', 'DPV_PTRHS', 6; ...
	'7', 'DPV_PTRHS', 7; ...
	'8', 'DPV_PTRHS', 8; ...
	'9', 'DPV_PTRHS', 9; ...
	'10', 'DPV_PTRHS', 10; ...
	'11', 'DPV_PTRHS', 11 }, 'Status', varargin{:} );
