function phtwme_stalelpvs(varargin);
% phtwme_stalelpvs( [...] );
% ME Stale LPV Stale
h = timeplot({'LPV_Stale'}, ...
      'ME Stale LPV Stale', ...
      'LPV Stale', ...
      {'LPV\_Stale'}, ...
      varargin{:} );
